/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

struct Element{
    int type;
    char key[254];
    char value1[254];
    int value2;
    float value3;
    struct Element* pNext;
};

//GLOBALS ----------
struct Element tmp;
struct Element* pHead = NULL;


//FUNCTIONS  DECLARATIONS  -------------
int addNode(char* key, char* value1, int* value2, float* value3);
int modifyNode(char* key, char* value1, int* value2, float* value3);
int deleteList(void);
int searchList(char* _key);
int deleteElement(char* key);
struct Element* getValue(char* key);
int numElements(void);

int *
innit_1(rqstp)
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
set_value_1(key, val1, val2, val3, rqstp)
	char *key;
	char *val1;
	int val2;
	float val3;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

getval *
get_value_1(key, rqstp)
	char *key;
	struct svc_req *rqstp;
{

	static getval result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
modify_value_1(key, val1, val2, val3, rqstp)
	char *key;
	char *val1;
	int val2;
	float val3;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
delete_key_1(key, rqstp)
	char *key;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
exist_1(key, rqstp)
	char *key;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
num_items_1(rqstp)
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
