/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
innit_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, innit, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_1(char *key, char *val1, int val2, float val3, int *clnt_res,  CLIENT *clnt)
{
	set_value_1_argument arg;
	arg.key = key;
	arg.val1 = val1;
	arg.val2 = val2;
	arg.val3 = val3;
	return (clnt_call (clnt, set_value, (xdrproc_t) xdr_set_value_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_1(char *key, getval *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_value,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &key,
		(xdrproc_t) xdr_getval, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_1(char *key, char *val1, int val2, float val3, int *clnt_res,  CLIENT *clnt)
{
	modify_value_1_argument arg;
	arg.key = key;
	arg.val1 = val1;
	arg.val2 = val2;
	arg.val3 = val3;
	return (clnt_call (clnt, modify_value, (xdrproc_t) xdr_modify_value_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_1(char *key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_key,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_1(char *key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
num_items_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, num_items, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}
