/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct getval {
	int res;
	char *val1;
	int val2;
	float val3;
};
typedef struct getval getval;
#ifdef __cplusplus
extern "C" bool_t xdr_getval(XDR *, getval*);
#elif __STDC__
extern  bool_t xdr_getval(XDR *, getval*);
#else /* Old Style C */
bool_t xdr_getval();
#endif /* Old Style C */


struct set_value_1_argument {
	char *key;
	char *val1;
	int val2;
	float val3;
};
typedef struct set_value_1_argument set_value_1_argument;
#ifdef __cplusplus
extern "C" bool_t xdr_set_value_1_argument(XDR *, set_value_1_argument);
#elif __STDC__
extern  bool_t xdr_set_value_1_argument(XDR *, set_value_1_argument);
#else /* Old Style C */
bool_t xdr_set_value_1_argument();
#endif /* Old Style C */


struct modify_value_1_argument {
	char *key;
	char *val1;
	int val2;
	float val3;
};
typedef struct modify_value_1_argument modify_value_1_argument;
#ifdef __cplusplus
extern "C" bool_t xdr_modify_value_1_argument(XDR *, modify_value_1_argument);
#elif __STDC__
extern  bool_t xdr_modify_value_1_argument(XDR *, modify_value_1_argument);
#else /* Old Style C */
bool_t xdr_modify_value_1_argument();
#endif /* Old Style C */


#define COM ((rpc_uint)99)
#define COMVER ((rpc_uint)1)

#ifdef __cplusplus
#define innit ((rpc_uint)1)
extern "C" int * innit_1(CLIENT *);
extern "C" int * innit_1_svc(struct svc_req *);
#define set_value ((rpc_uint)2)
extern "C" int * set_value_1(char *, char *, int , float , CLIENT *);
extern "C" int * set_value_1_svc(char *, char *, int , float , struct svc_req *);
#define get_value ((rpc_uint)3)
extern "C" getval * get_value_1(char *, CLIENT *);
extern "C" getval * get_value_1_svc(char *, struct svc_req *);
#define modify_value ((rpc_uint)4)
extern "C" int * modify_value_1(char *, char *, int , float , CLIENT *);
extern "C" int * modify_value_1_svc(char *, char *, int , float , struct svc_req *);
#define delete_key ((rpc_uint)5)
extern "C" int * delete_key_1(char *, CLIENT *);
extern "C" int * delete_key_1_svc(char *, struct svc_req *);
#define exist ((rpc_uint)6)
extern "C" int * exist_1(char *, CLIENT *);
extern "C" int * exist_1_svc(char *, struct svc_req *);
#define num_items ((rpc_uint)7)
extern "C" int * num_items_1(CLIENT *);
extern "C" int * num_items_1_svc(struct svc_req *);

#elif __STDC__
#define innit ((rpc_uint)1)
extern  int * innit_1(CLIENT *);
extern  int * innit_1_svc(struct svc_req *);
#define set_value ((rpc_uint)2)
extern  int * set_value_1(char *, char *, int , float , CLIENT *);
extern  int * set_value_1_svc(char *, char *, int , float , struct svc_req *);
#define get_value ((rpc_uint)3)
extern  getval * get_value_1(char *, CLIENT *);
extern  getval * get_value_1_svc(char *, struct svc_req *);
#define modify_value ((rpc_uint)4)
extern  int * modify_value_1(char *, char *, int , float , CLIENT *);
extern  int * modify_value_1_svc(char *, char *, int , float , struct svc_req *);
#define delete_key ((rpc_uint)5)
extern  int * delete_key_1(char *, CLIENT *);
extern  int * delete_key_1_svc(char *, struct svc_req *);
#define exist ((rpc_uint)6)
extern  int * exist_1(char *, CLIENT *);
extern  int * exist_1_svc(char *, struct svc_req *);
#define num_items ((rpc_uint)7)
extern  int * num_items_1(CLIENT *);
extern  int * num_items_1_svc(struct svc_req *);

#else /* Old Style C */
#define innit ((rpc_uint)1)
extern  int * innit_1();
extern  int * innit_1_svc();
#define set_value ((rpc_uint)2)
extern  int * set_value_1();
extern  int * set_value_1_svc();
#define get_value ((rpc_uint)3)
extern  getval * get_value_1();
extern  getval * get_value_1_svc();
#define modify_value ((rpc_uint)4)
extern  int * modify_value_1();
extern  int * modify_value_1_svc();
#define delete_key ((rpc_uint)5)
extern  int * delete_key_1();
extern  int * delete_key_1_svc();
#define exist ((rpc_uint)6)
extern  int * exist_1();
extern  int * exist_1_svc();
#define num_items ((rpc_uint)7)
extern  int * num_items_1();
extern  int * num_items_1_svc();
#endif /* Old Style C */

#endif /* !_CALC_H_RPCGEN */
