/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
com_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	enum clnt_stat retval_2;
	int result_2;
	char *set_value_1_key;
	char *set_value_1_val1;
	int set_value_1_val2;
	float set_value_1_val3;
	enum clnt_stat retval_3;
	getval result_3;
	char *get_value_1_key;
	enum clnt_stat retval_4;
	int result_4;
	char *modify_value_1_key;
	char *modify_value_1_val1;
	int modify_value_1_val2;
	float modify_value_1_val3;
	enum clnt_stat retval_5;
	int result_5;
	char *delete_key_1_key;
	enum clnt_stat retval_6;
	int result_6;
	char *exist_1_key;
	enum clnt_stat retval_7;
	int result_7;

#ifndef	DEBUG
	clnt = clnt_create (host, COM, COMVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = innit_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = set_value_1(set_value_1_key, set_value_1_val1, set_value_1_val2, set_value_1_val3, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = get_value_1(get_value_1_key, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = modify_value_1(modify_value_1_key, modify_value_1_val1, modify_value_1_val2, modify_value_1_val3, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = delete_key_1(delete_key_1_key, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = exist_1(exist_1_key, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = num_items_1(&result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	com_1 (host);
exit (0);
}
